import type { Feature, FeatureCollection, Geometry } from "geojson";

/** Shape of src/content/hobbies/content.json (all hand-written text and lists). */
export type Gear = { name: string; type: string; photo: string | null };
export type HobbiesContent = {
  page: { title: string; intro: string };
  music: {
    kicker: string;
    blurb: string;
    guitars: Gear[];
    stage: { name: string; photo: string | null }[];
  };
  outdoors: {
    kicker: string;
    blurb: string;
    states: string[];
    parks: { name: string; lat: number; lon: number }[];
    countries: { name: string; geoName: string; focus?: [number, number]; marker?: boolean }[];
  };
  photography: {
    kicker: string;
    blurb: string;
    categories: string[];
    cameras: Gear[];
    photos: { title: string; category: string; favorite: boolean; src: string | null }[];
  };
};

/** src/content/hobbies/music-stats.json (rewritten daily from Spotify by scripts/spotify-stats.mjs). */
export type MusicStats = {
  sample: boolean;
  source?: string;
  ranges: {
    id: string;
    label: string;
    /** image: artist photo URL; url: the artist's Spotify page. */
    artists: { name: string; image?: string; url?: string }[];
    /** image: album cover URL; url: the track's Spotify page. */
    tracks: { title: string; artist: string; image?: string; url?: string }[];
  }[];
};

/** src/content/hobbies/outdoors-stats.json (rewritten later from Strava). */
export type OutdoorsStats = {
  sample: boolean;
  year: number;
  milesThisYear: number;
  milesAllTime: number;
  milesByMonth: number[];
};

/** Generated by `npm run build:geo`. */
export type GeoUS = {
  states: { n: string; d: string; v: boolean }[];
  parks: { n: string; x: number; y: number }[];
  parkView: [number, number, number, number];
};
export type GeoWorld = {
  land: Feature<Geometry>;
  visited: FeatureCollection<Geometry>;
  countries: { n: string; c: [number, number]; dot: [number, number] | null }[];
};

export type HobbiesData = {
  content: HobbiesContent;
  music: MusicStats;
  outdoors: OutdoorsStats;
  geoUS: GeoUS;
};

export const fmt = (n: number) => Number(n).toLocaleString("en-US");
