#!/usr/bin/env node
/**
 * Rewrites src/content/hobbies/music-stats.json with Colin's top 10 Spotify artists and tracks.
 * Run by .github/workflows/spotify-stats.yml; can also be run locally with the same env vars:
 *   SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, SPOTIFY_REFRESH_TOKEN  (see scripts/spotify-auth.mjs)
 *
 * Two of Spotify's ranges become the page's range chips, in this order. Each entry also gets its
 * Spotify image (artist photo / album cover, hotlinked from Spotify's CDN) and Spotify page URL.
 * The file is only rewritten when the lists change, so unchanged days produce no commit.
 */
import fs from "node:fs";
import path from "node:path";

const OUT = path.join(import.meta.dirname, "..", "src/content/hobbies/music-stats.json");
const RANGES = [
  { id: "recent", label: "Recently", spotify: "short_term" }, // about the last 4 weeks
  { id: "year", label: "This year", spotify: "long_term" }, // about the last 12 months
];
// Thumbnails show at 28px (56px on high-density screens): take the smallest image at least 64px wide.
const pickImage = (images = []) => {
  const bySize = [...images].sort((a, b) => (a.width ?? 0) - (b.width ?? 0));
  return (bySize.find((i) => (i.width ?? 0) >= 64) ?? bySize.at(-1))?.url;
};
const LIMIT = 10;

const { SPOTIFY_CLIENT_ID: id, SPOTIFY_CLIENT_SECRET: secret, SPOTIFY_REFRESH_TOKEN: refresh } = process.env;
if (!id || !secret || !refresh) {
  // Not set up yet: skip quietly instead of failing every scheduled run.
  console.log("::warning::Spotify secrets are not set (SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, SPOTIFY_REFRESH_TOKEN). Skipping.");
  process.exit(0);
}

const tokenRes = await fetch("https://accounts.spotify.com/api/token", {
  method: "POST",
  headers: {
    "content-type": "application/x-www-form-urlencoded",
    authorization: "Basic " + Buffer.from(`${id}:${secret}`).toString("base64"),
  },
  body: new URLSearchParams({ grant_type: "refresh_token", refresh_token: refresh }),
});
const token = await tokenRes.json().catch(() => ({}));
if (!tokenRes.ok || !token.access_token) {
  console.error(
    `Could not get a Spotify access token (${tokenRes.status} ${token.error || ""}: ${token.error_description || ""}).\n` +
      "If the refresh token was revoked or expired, run `node scripts/spotify-auth.mjs` again and update SPOTIFY_REFRESH_TOKEN.",
  );
  process.exit(1);
}
if (token.refresh_token && token.refresh_token !== refresh) {
  console.log("::warning::Spotify issued a new refresh token. The current one still worked; if runs start failing, rerun scripts/spotify-auth.mjs.");
}

async function top(kind, range) {
  const url = `https://api.spotify.com/v1/me/top/${kind}?` + new URLSearchParams({ time_range: range, limit: String(LIMIT) });
  const res = await fetch(url, { headers: { authorization: `Bearer ${token.access_token}` } });
  if (!res.ok) throw new Error(`GET ${url} failed: ${res.status} ${await res.text()}`);
  return (await res.json()).items ?? [];
}

const ranges = [];
for (const r of RANGES) {
  const [artists, tracks] = await Promise.all([top("artists", r.spotify), top("tracks", r.spotify)]);
  ranges.push({
    id: r.id,
    label: r.label,
    artists: artists.map((a) => ({ name: a.name, image: pickImage(a.images), url: a.external_urls?.spotify })),
    tracks: tracks.map((t) => ({
      title: t.name,
      artist: t.artists.map((a) => a.name).join(", "),
      image: pickImage(t.album?.images),
      url: t.external_urls?.spotify,
    })),
  });
}

if (ranges.every((r) => r.artists.length === 0 && r.tracks.length === 0)) {
  console.error("Spotify returned no top artists or tracks for any range; keeping the current file.");
  process.exit(1);
}

const prev = JSON.parse(fs.readFileSync(OUT, "utf8"));
if (prev.source === "spotify" && JSON.stringify(prev.ranges) === JSON.stringify(ranges)) {
  console.log("No change in top artists or tracks.");
  process.exit(0);
}

const next = {
  _readme:
    "Listening stats from Spotify. GENERATED by scripts/spotify-stats.mjs (daily GitHub Action); do not hand-edit. Ranges: Recently = Spotify short_term (about 4 weeks), This year = long_term (about 12 months); top 10 each, with Spotify image and page URLs.",
  sample: false,
  updated: new Date().toISOString().slice(0, 10),
  source: "spotify",
  ranges,
};
fs.writeFileSync(OUT, JSON.stringify(next, null, 2) + "\n");
console.log(`Updated ${path.relative(process.cwd(), OUT)}:`);
for (const r of ranges) console.log(`  ${r.label}: ${r.artists.map((a) => a.name).slice(0, 3).join(", ")}...`);
